package app.anne.user.infrastructure;

import app.anne.user.domain.model.User;
import app.anne.user.domain.model.UserId;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;
import java.util.List;

@DynamoDbBean
@Getter
@Setter
@ToString
public class UserRecord {

    public static String getPartitionKeyValue(UserId userId) {
        return "USER#" + userId.getValue();
    }

    public static UserRecord convertFrom(User entity) {
        UserRecord record = new UserRecord();
        record.pk = UserRecord.getPartitionKeyValue(entity.getUser());
        record.sk = "USER";
        record.userId = entity.getUser().getValue();
        record.email = entity.getEmail();
        record.name = entity.getName();
        record.mobile = entity.getMobile();
        record.description = entity.getDescription();
        record.picture = entity.getPicture();
        record.locations = entity.getLocations();
        record.updatedAt = entity.getUpdatedAt();
        return record;
    }

    private String pk;
    private String sk;
    private String userId;
    private String email;
    private String name;
    private String mobile;
    private String description;
    private String picture;
    private List<String> locations;
    private Instant updatedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("PK")
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("SK")
    public String getSk() {
        return sk;
    }

    @DynamoDbAttribute("email")
    public String getEmail() {
        return email;
    }

    @DynamoDbAttribute("name")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute("mobile")
    public String getMobile() {
        return mobile;
    }

    @DynamoDbAttribute("description")
    public String getDescription() {
        return description;
    }

    @DynamoDbAttribute("picture")
    public String getPicture() {
        return picture;
    }

    @DynamoDbAttribute("locs")
    public List<String> getLocations() {
        return locations;
    }

    @DynamoDbAttribute("ut")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
