package app.anne.place.infrastructure;

import app.anne.place.domain.model.Address;
import app.anne.place.domain.model.GeoLocation;
import app.anne.place.domain.model.Place;
import app.anne.place.domain.model.PlaceId;
import lombok.NoArgsConstructor;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;
import java.util.List;

@DynamoDbBean
@NoArgsConstructor
@Setter
public class PlaceRecord {

    public static String getPartitionKeyValue(PlaceId placeId) {
        return String.format("PLC#%s", placeId.getValue());
    }

    public static String getSortKeyValue() {
        return "PLACE";
    }

    public static Place convertToEntity(PlaceRecord record) {
        Address address = Address.builder()
                .fullAddress(record.getAddress())
                .roadAddress(record.getRoadAddress())
                .build();

        GeoLocation geoLocation;
        if (record.getGeo() == null) {
            geoLocation = GeoLocation.createNullObject();
        } else {
            geoLocation = new GeoLocation(
                    GeoLocation.Type.valueOf(record.getGeo().getType()),
                    record.getGeo().getX(),
                    record.getGeo().getY());
        }

        return Place.builder()
                .id(new PlaceId(record.getId()))
                .name(record.getName())
                .category(record.getCategory())
                .description(record.getDescription())
                .telephone(record.getTelephone())
                .address(address)
                .locations(record.getLocations())
                .geoLocation(geoLocation)
                .link(record.getLink())
                .build();
    }

    private String pk;
    private String sk;
    private String id;
    private String name;
    private String category;
    private String description;
    private String telephone;
    private String address;
    private String roadAddress;
    private List<String> locations;
    private GeoRecord geo;
    private String link;
    private Instant updatedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("PK")
    @DynamoDbSecondarySortKey(indexNames = {"Inverted"})
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("SK")
    @DynamoDbSecondaryPartitionKey(indexNames = {"Inverted"})
    public String getSk() {
        return sk;
    }

    @DynamoDbAttribute("plcId")
    public String getId() {
        return id;
    }

    @DynamoDbAttribute("plcNm")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute("catg")
    public String getCategory() {
        return category;
    }

    @DynamoDbAttribute("desc")
    public String getDescription() {
        return description;
    }

    @DynamoDbAttribute("tel")
    public String getTelephone() {
        return telephone;
    }

    @DynamoDbAttribute("addr")
    public String getAddress() {
        return address;
    }

    @DynamoDbAttribute("rdAddr")
    public String getRoadAddress() {
        return roadAddress;
    }

    @DynamoDbAttribute("locs")
    public List<String> getLocations() {
        return locations;
    }

    @DynamoDbAttribute("geo")
    public GeoRecord getGeo() {
        return geo;
    }

    @DynamoDbAttribute("link")
    public String getLink() {
        return link;
    }

    @DynamoDbAttribute("ut")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
