package app.anne.channel.infrastructure;

import app.anne.channel.domain.model.Channel;
import app.anne.channel.domain.model.ChannelId;
import app.anne.channel.domain.model.Moderator;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;
import java.util.List;

@DynamoDbBean
@Getter
@Setter
@ToString
public class ChannelRecord {

    public static String getPartitionKeyValue(ChannelId channelId) {
        return "CHANNEL#" + channelId.getValue();
    }

    public static ChannelRecord convertFrom(Channel entity) {
        ChannelRecord record = new ChannelRecord();
        record.pk = ChannelRecord.getPartitionKeyValue(entity.getChannel());
        record.sk = "CHANNEL";
        record.channelId = entity.getChannel().getValue();
        record.name = entity.getName();
        record.description = entity.getDescription();
        record.imageUrl = entity.getImageUrl();
        record.moderators = entity.getModerators();
        record.updatedAt = entity.getUpdatedAt();
        return record;
    }

    private String pk;
    private String sk;
    private String gsi1Pk;
    private String gsi1Sk;
    private String channelId;
    private String name;
    private String description;
    private String imageUrl;
    private List<Moderator> moderators;
    private Instant updatedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("PK")
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("SK")
    public String getSk() {
        return sk;
    }

    @DynamoDbAttribute("GSI1_PK")
    @DynamoDbSecondaryPartitionKey(indexNames = {"GSI1"})
    public String getGsi1Pk() {
        return gsi1Pk;
    }

    @DynamoDbAttribute("GSI1_SK")
    @DynamoDbSecondarySortKey(indexNames = {"GSI1"})
    public String getGsi1Sk() {
        return gsi1Sk;
    }

    @DynamoDbAttribute("name")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute("description")
    public String getDescription() {
        return description;
    }

    @DynamoDbAttribute("imageUrl")
    public String getImageUrl() {
        return imageUrl;
    }

    @DynamoDbAttribute("moderators")
    public List<Moderator> getModerators() {
        return moderators;
    }

    @DynamoDbAttribute("ut")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }

}
