package app.anne.channel.infrastructure;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

import app.anne.channel.domain.model.ChannelId;
import app.anne.channel.domain.model.Member;
import app.anne.channel.domain.model.MemberId;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@DynamoDbBean
@Getter
@Setter
@ToString
public class MemberRecord {

    public static String getPartitionKeyValue(ChannelId channelId) {
        return "CHANNEL#" + channelId.getValue();
    }

    public static String getSortKeyValue(MemberId memberId) {
        return "MEMBER#" + memberId.getValue();
    }

    public static MemberRecord convertFrom(Member entity) {
        MemberRecord record = new MemberRecord();
        record.pk = MemberRecord.getPartitionKeyValue(entity.getChannel());
        record.sk = MemberRecord.getSortKeyValue(entity.getMember());
        record.channelId = entity.getChannel().getValue();
        record.memberId = entity.getMember().getValue();
        record.name = entity.getName();
        record.imageUrl = entity.getImageUrl();
        record.updatedAt = entity.getUpdatedAt();
        return record;
    }

    private String pk;
    private String sk;
    private String channelId;
    private String memberId;
    private String name;
    private String imageUrl;
    private Instant updatedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("PK")
    @DynamoDbSecondarySortKey(indexNames = {"Inverted"})
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("SK")
    @DynamoDbSecondaryPartitionKey(indexNames = {"Inverted"})
    public String getSk() {
        return sk;
    }

    @DynamoDbAttribute("name")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute("imageUrl")
    public String getImageUrl() {
        return imageUrl;
    }


    @DynamoDbAttribute("ut")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}