package app.anne.channel.infrastructure;

import java.time.Instant;

import app.anne.channel.domain.model.ChannelId;
import app.anne.channel.domain.model.Message;
import app.anne.channel.domain.model.MessageId;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@DynamoDbBean
@Getter
@Setter
@ToString
public class MessageRecord {
    
    public static String getPartitionKeyValue(ChannelId channelId) {
        return "CHANNEL#" + channelId.getValue();
    }

    public static String getSortKeyValue(MessageId messageId) {
        return "MESSAGE#" + messageId.getValue();
    }

    public static MessageRecord convertFrom(Message entity) {
        MessageRecord record = new MessageRecord();
        record.pk = MessageRecord.getPartitionKeyValue(entity.getChannel());
        record.sk = MessageRecord.getSortKeyValue(entity.getMessage());
        record.channelId = entity.getChannel().getValue();
        record.messageId = entity.getMessage().getValue();
        record.body = entity.getBody();
        record.sender = entity.getSender();
        record.updatedAt = entity.getUpdatedAt();
        return record;
    }

    private String pk;
    private String sk;
    private String channelId;
    private String messageId;
    private String body;
    private String sender;
    private Instant updatedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("PK")
    public String getPk() {
        return pk;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("SK")
    public String getSk() {
        return sk;
    }

    @DynamoDbAttribute("body")
    public String getBody() {
        return body;
    }

    @DynamoDbAttribute("sender")
    public String getSender() {
        return sender;
    }

    @DynamoDbAttribute("ut")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
